### PR TITLE
Update front readme

### LINKED ISSUE #13: Create some Pitch text for the project landing page

### PR DESCRIPTION
**Pull request by jpound**
I've redone the readme with some more text to describe the overall benefits and give a quick synopsis of each layer. I welcome any suggestions for changes.

Closes #13

### CODE REVIEW

**Review by TylerMizuyabu — DISMISSED** [review]

**Review by bzarboni1 — APPROVED** [review]
Looks great Joe. Sounds even better!

**Comment by blastdan** [comment]
I'd like to add a "sudo" roadmap to the font as well.

Currently Support Clouds
Features Enabled
Future Features Planned
Etc.

It would be a good idea to include some kind of section that details the tools and versions being used as well near the bottom.

**Comment by jpound** [comment]
> I'd like to add a "sudo" roadmap to the font as well.
> 
> 
> 
> Currently Support Clouds
> 
> Features Enabled
> 
> Future Features Planned
> 
> Etc.
> 
> 
> 
> It would be a good idea to include some kind of section that details the tools and versions being used as well near the bottom.

Sounds good to me. @TylerMizuyabu if you have a sec can you reply with a list and I'll get it formatted and included? So far I know Terraform and Terragrunt.

**Comment by blastdan** [comment]
I asked Gemini to help.

Here are the generated docs


Securely Manage Your Enterprise's GitHub Environment at Scale
Problem:

Running a large enterprise on GitHub can be a security nightmare. Maintaining consistent configurations across multiple organizations is a challenge. Updates take days or weeks, and inconsistencies create blind spots for security vulnerabilities.

Introducing the GitHub Foundations Toolkit

The GitHub Foundations Toolkit empowers you to manage your enterprise's GitHub environment with unparalleled security and efficiency.  This open-source project provides a comprehensive set of tools to:

Automate Secure Infrastructure: Set up and manage multiple organizations under a single GitHub Enterprise account using Infrastructure as Code (IaC) principles with Terraform. Establish consistent security best practices by default.
Centralized Control: Gain a single pane of glass view for managing configurations, teams, and cloud provider settings across all your organizations.
Rapid Rollouts: Streamline updates and enforce security policies consistently across your entire enterprise, eliminating the need for time-consuming manual intervention by individual organizations.
Continuous Security: Leverage drift detection to identify unauthorized changes and ensure your configurations remain secure.
Benefits:

Reduced Security Risk: Enforce consistent security policies across all your organizations, minimizing the attack surface.
Improved Efficiency: Automate repetitive tasks and streamline updates, freeing up your team to focus on innovation.
Centralized Visibility: Gain a consolidated view of your entire GitHub environment for better decision-making.
Open Source and Customizable: Tailor the toolkit to your specific needs and contribute to its ongoing development.
Features:

Current:

[ ] GCP Backend: Leverages Google Cloud Platform for infrastructure provisioning. (Future support for Azure and AWS coming soon!)
[ ] Terraform and Terragrunt: Utilizes industry-standard tools for managing infrastructure as code.
[ ] Repository Management: Automate creation, deletion, and configuration of repositories (private and public).
[ ] Team Management: Efficiently manage teams and team memberships across organizations.
[ ] Secret Management: Securely store and manage sensitive secrets within your GitHub environment.
[ ] Rolesets for Branch Protection: Enforce granular access control through pre-configured rolesets.
Future:

[ ] Multi-Cloud Support: Seamless integration with Azure and AWS cloud providers.
[ ] Enhanced Security Features: Explore additional security functionalities based on community needs.
Getting Started:

This repository is organized into 2 layers:

Bootstrap Layer: Sets up GCP and creates all organizations under your GitHub Enterprise account.
Organizations Layer: Manages configurations, teams, cloud provider settings, drift detection, and pull request plan execution for your organizations.
Embrace a Secure and Efficient Future with the GitHub Foundations Toolkit!

Call to Action:

Star this repository to show your support!
Contribute to the project's development: We leverage Terraform and Terragrunt for infrastructure as code. If you're familiar with these tools, we welcome your contributions! Check out the contributing guidelines [CONTRIBUTING_GUIDE.md] for details.
Join our community to share best practices and get help.
Developer Section:

We're committed to building a robust open-source toolkit for managing enterprise GitHub environments. If you're interested in contributing, we welcome your help! Here's how you can get involved:

Bug Fixes and Improvements: Identify and address any bugs you encounter.
New Features: Propose and implement functionalities that align with our roadmap or address community needs.
Documentation: Improve the clarity and comprehensiveness of our documentation.
Testing: Help us ensure the quality and reliability of the toolkit by writing unit and integration tests.
Please refer to the contributing guidelines [CONTRIBUTING_GUIDE.md] for detailed instructions on setting up your development environment and submitting pull requests.

Note: Replace [CONTRIBUTING_GUIDE.md] with the actual filename of your contributing guide.

**Review by bzarboni1 — APPROVED** [review]

**Pull request merged**
